home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path("home/", views.home, name="home"),
]

taskie/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('', include("user_manager.urls")),
]

user_manager/urls.py
from django.urls import path
from . import views

app_name = 'user_manager'
urlpatterns = [
    # path("", views.index, name="index"),
    path("", views.welcome, name="welcome"),
    path("signin/", views.signin, name="signin"),
    path("signup/", views.signup, name="signup"),
    path("signout/", views.signout, name="signout"),
]

home/models.py
from django.db import models

# Create your models here.

user_manager/models.py
from django.db import models

# Create your models here.

user_manager/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username', 'first_name', 'last_name', 'password1', 'password2'
        ]
        labels = {
            'username' : 'Usuario',
            'first_name' : 'Nombres',
            'last_name' : 'Apellidos',
            'password' : 'Contraseña',
            'password2' : 'Repetir Contraseña',
        }
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Ej: JuanPedro1718'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'Ej: Juan Pedro'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Ej: Pérez Machuca'}),
            'password1': forms.PasswordInput(attrs={'placeholder': 'Contraseña'}),
            'password2': forms.PasswordInput(attrs={'placeholder': 'Repita su contraseña'})
        }

        help_texts = {
            'username' : 'Debe contener letras, números y @.',
            'password1': 'Ingrese su contraseña.',
            'password2': 'Vuelva a ingresar su contraseña.',
        }

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    context = {}
    return render(request, "home/home.html", context)

user_manager/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm

from .forms import *

# Create your views here.
def index(request):
    context = {}
    # return render(request, "index.html", context)

def welcome(request):
    context = {}
    return render(request, 'welcome.html', context)

def signin(request):
    if request.method == 'GET':
        context = {'form': AuthenticationForm}
        return render(request, 'auth/signin.html', context)
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return JsonResponse({'success': False, 'error': 'El usuario o la contraseña son incorrectos'})
        else:
            login(request, user)
            return JsonResponse({'success': True})


from django.http import JsonResponse

def signup(request):
    if request.method == 'POST':
        formulario_post = CustomCreationForm(request.POST)
        if formulario_post.is_valid():
            user = formulario_post.save()
            login(request, user)
            return JsonResponse({'success': True})
        else:
            # Return form errors as JSON response
            return JsonResponse({'success': False, 'errors': formulario_post.errors})
    else:
        return render(request, 'auth/signup.html', {
            'form' : CustomCreationForm()
        })


def signout(request):
    logout(request)
    return redirect('home:home')

home/templates/home/home.html
{% extends '../layouts/base.html' %}
{% load static %}

{% block title %}Taskie Task Manager{% endblock title %}

{% block content %}

<div class="container">
  <h1>Home Page</h1>
</div>

{% endblock content %}

home/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock styles %}
    {% block scripts %}{% endblock scripts %}
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body class="d-flex flex-column h-100">
    <header>
        {% include 'layouts/partials/navbar.html' %}
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <footer class="mt-auto">
        {% include 'layouts/partials/footer.html' %}
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
</body>
</html>

home/templates/layouts/partials/footer.html
{% load static %}
<div class="footer d-flex flex-wrap justify-content-between align-items-center px-4 py-3 border-top bg-light bg-opacity-25">
    <p class="col-md-4 mb-0 text-body-secondary">© 2023 Todos los derechos reservados</p>
    <a href="#" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img class="bi me-2 text-dark" src={% static "img/logo-black.svg" %} alt="Logo" width="40" height="32" >
    </a>
    <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item">
            <a href="#" class="nav-link px-2 text-body-secondary">Inicio</a>
        </li>
    </ul>
</div>

home/templates/layouts/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark px-3 bg-secondary bg-opacity-50">
    <div class="container-fluid">
        <a class="navbar-brand " href="{% url 'home:home' %}">
            <img src={% static "img/logo.svg" %} alt="" width="35" height="35" class="d-inline-block align-text-top logo">
            Taskie
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="ms-auto bg-secondary bg-opacity-25 rounded p-0 m-0">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Inicio</a>
                    </li>
                    <hr class="vhr">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    {% if user.is_authenticated %}
                    <hr class="vhr">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_manager:signout' %}">Log out</a>
                    </li>
                    {% else %}
                    <hr class="vhr">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_manager:signin' %}">Log in</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>

user_manager/templates/layouts/baseLogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/welcome.css' %}">
    

    {% block styles %}{% endblock styles %}
    {% block scripts %}{% endblock scripts %}
    
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body >

    <header>
        {% block header %}{% endblock header %}
    </header>

    <main>
        {% block content %}{% endblock content %}
    </main>

    {% block modals %}{% endblock modals %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
</body>
</html>

user_manager/templates/layouts/partials/loginModal.html
{% extends 'layouts/partials/modalTemplate.html' %}

{% block name_modal %}loginModal{% endblock name_modal %}
{% block iframe_modal %}
    <iframe src="{% url 'user_manager:signin' %}" width="100%" height="300px" frameborder="0"> </iframe>
{% endblock iframe_modal %}

user_manager/templates/layouts/partials/modalTemplate.html
{% load static %}

<div class="modal scale-up-vertical-center model_container_card" id="{% block name_modal %}{% endblock name_modal %}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
    <div class="modal-content modal_card border-0 rounded-0">
      <div class="modal-header border-0">
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body scroll_modal">
        {% block iframe_modal %}
        {% endblock iframe_modal %}
      </div>
    </div>
  </div>
</div>

user_manager/templates/layouts/partials/registerModal.html
{% extends 'layouts/partials/modalTemplate.html' %}

{% block name_modal %}registerModal{% endblock name_modal %}

{% block iframe_modal %}
    <iframe src="{% url 'user_manager:signup' %}" width="100%" height="500px" frameborder="0"></iframe>
{% endblock iframe_modal %}

user_manager/templates/welcome.html
{% extends './layouts/baseLogin.html' %}
{% load static %}
{% block title %}Login{% endblock title %}

{% block header %}
    <a  href=" {% url 'home:home' %} "><img class="logo" width="35" height="35" src=" {% static 'img/logo.svg' %} " alt="Inicio"></a>
{% endblock header %}

{% block content %}
<div class="loginBackground">
    <div class="container d-flex align-items-center justify-content-center vh-100">
        <div class="text-center">
            <img src="{% static 'img/logo-color.png' %}" alt="Logo de la App" class="img-fluid" width="200">
            <h1 class="mt-4">¡Bienvenido a Taskie!</h1>
            <p class="lead">Haz más, preocúpate menos.</p>
            <div class="mt-4">
                <a href="#" class="btn btn-outline-primary btn-lg" data-bs-toggle="modal" data-bs-target="#loginModal">Iniciar Sesión</a>
                <a href="#" class="btn btn-outline-info  btn-lg" data-bs-toggle="modal" data-bs-target="#registerModal">Crear una cuenta</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}




{% block modals %}

{% include 'layouts/partials/loginModal.html' %}
{% include 'layouts/partials/registerModal.html' %}

{% endblock modals %}

{% block scripts %}

<script>
    const loginModal = document.getElementById('loginModal')
    const myInput = document.getElementById('myInput')

    loginModal.addEventListener('shown.bs.modal', () => {
    myInput.focus()
    })
</script>
<script>
    const registerModal = document.getElementById('registerModal')
    const myInput = document.getElementById('myInput')

    registerModal.addEventListener('shown.bs.modal', () => {
    myInput.focus()
    })
</script>




{% endblock scripts %}